//
// Created by pospelov on 04.02.2021.
//

#ifndef GUI_BUILDER_GRAPHICS_GUI_HOVERABLE_HPP_
#define GUI_BUILDER_GRAPHICS_GUI_HOVERABLE_HPP_

class Hoverable {
};

#endif//GUI_BUILDER_GRAPHICS_GUI_HOVERABLE_HPP_
